### ISSUE TITLE
Thermal diagram of key frame

### ISSUE THREAD

**Issue by zhou-bt** [bomri/SlowFast#11]
hi  @author

How to draw the thermal diagram of the key frame in the paper.

I would appreciate it if you could tell me.

**Comment by bomri** [comment]
Hi @zhou-bt,

The input size (sequence length) of the attention layers is the same as its output, so you can align each sample in the sequence to its attention weight. We explain this in the paper: "...Further, we visualize the [CLS] token attention weights by processing the same video from Fig. 2 with the single-head trained network and depicted, in Fig. 3, all the weights of the first attention layer aligned to the video’s frames."
