### ISSUE TITLE
Unable to load weights of the 'VIT_B_VTN' model

### ISSUE THREAD

**Issue by shardulparab97** [bomri/SlowFast#12]
While trying to test run_net.py using the weights **'VTN_VIT_B_KINETICS.pyth'** (available from the model zoo link, I am unable to load the weights. I am getting the error as - **"PytorchStreamReader failed reading zip archive: failed finding central directory"** and unable to proceed further.

Would like to request help for the same, thanks! :)

**Comment by bomri** [comment]
Hi @shardulparab97,
Does it work when you only try to load the file:
`import torch`
`torch.load("VTN_VIT_B_KINETICS.pyth")`

Also, what version of torch are you using?
