### ISSUE TITLE
VTN input example

### ISSUE THREAD

**Issue by santiagoRuizSchiphol** [bomri/SlowFast#15]
Hello,

I am trying to setup the VTN model for training. For that I am digging into the model's architecture, specifically the model's forward function. But I am struggling to understand how the input values should be constructed, specifically what the `position_ids` is and how it is calculated. I have tried to look in the internet for examples and it seems that there is none.

If you can help me with a simple example, that would be great. I also can help by adding documentation to this bit of code.

**Comment by bomri** [comment]
Hi @santiagoRuizSchiphol, 
Please take a look at #6, I think it will answer your question.
Let me know if you still struggle to construct the `position_ids` in your setup.

**Comment by santiagoRuizSchiphol** [comment]
Hello @bomri,

Thank you for your answer, it was quite helpful. 

If you want I can help to improve this nice project in at least two ways:
- Add documentation to the `forward` function of the VTN model
- Make the argument `position_ids` optional to have a similar behaviour as is explained in Huggin Face glossary ([here the link](https://huggingface.co/transformers/v3.2.0/glossary.html))

**Comment by bomri** [comment]
Sure, that will be great :)

**Comment by santiagoRuizSchiphol** [comment]
All right! I will work on it next week then.
