### ISSUE TITLE
How to use Resnet as backbone?

### ISSUE THREAD

**Issue by 2605759123** [bomri/SlowFast#16]
Hi, Thank for your works.
I want to know how to use resnet as the backbone as mentioned in the paper. 
Should I drop full-connect layer or/and avg-pooling layer of Resnet?
<img width="785" alt="image" src="https://user-images.githubusercontent.com/43004851/207006843-c10cdd7a-ce43-4f13-bb41-3ac65cb987f7.png">

**Comment by bomri** [comment]
Hi @2605759123,
You should drop the FC layer and use only the network features.
You can do it easily by loading PyTorch ResNet model weights and changing the FC layer to an identity layer:

```
from torch import nn
import torchvision.models as models
model = models.resnet50(pretrained=pretrained)
model.fc = nn.Identity()
```

**Comment by 2605759123** [comment]
Thank you~
