### ISSUE TITLE
Position IDs in VTN

### ISSUE THREAD

**Issue by rayush7** [bomri/SlowFast#6]
Hi @bomri 

Thanks for the code. Could you please explain what is position_ids (and their shape) in VTN code here?
https://github.com/bomri/SlowFast/blob/master/slowfast/models/video_model_builder.py#L825

Do I need to modify my dataloader to include the position_ids?

Thanks

**Comment by bomri** [comment]
Hi @rayush7,

The `position_ids` variable marks the "location" or position of each specific input in the sequence. For example, if you represent a video by a sequence of frames and use one frame per second the `position_ids` will refer to the second each frame was extracted from.

You will need to adjust your dataloader to include these values and return them in the `__getitem__`. You can look at [pack_pathway_output](https://github.com/bomri/SlowFast/blob/78691256781dc76c6a67773298412fe352e3b53f/slowfast/datasets/kinetics.py#L288) and follow up on how `frames_index` is created.

**Comment by zjjJacinthe** [comment]
@bomri Hi
I have read your paper and there's ab ablation study about position embedding.
However, I do not know how to build a VTN without PE or how to build a learnable PE.
Waiting for your reply, thanks a lot.
